# Base configuration for ShareThings Docker Compose

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - PORT=${API_PORT:-3001}
    container_name: share-things-backend  # Explicit container name
    hostname: backend  # Explicit hostname
    environment:
      - NODE_ENV=development
      - PORT=${API_PORT:-3001}
    ports:
      - "${BACKEND_PORT:-3001}:${API_PORT:-3001}"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      app_network:
        aliases:
          - backend  # Explicit network alias

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: share-things-frontend  # Explicit container name
    environment:
      - API_PORT=${API_PORT:-3001}
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      app_network:
        aliases:
          - frontend  # Explicit network alias

# Explicit network configuration
networks:
  app_network:
    driver: bridge