# Base configuration for ShareThings Docker Compose

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - PORT=${API_PORT:-3001}
    container_name: share-things-backend  # Explicit container name
    hostname: backend  # Explicit hostname
    environment:
      - NODE_ENV=development
      - PORT=${API_PORT:-3001}
      # Explicitly set the port to ensure it's used
      - LISTEN_PORT=${API_PORT:-3001}
    ports:
      - "${BACKEND_PORT:-3001}:${API_PORT:-3001}"
    volumes:
      - ./server:/app:Z
      - volume-backend-node-modules:/app/node_modules
    networks:
      app_network:
        aliases:
          - backend  # Explicit network alias

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - API_URL=auto
        - SOCKET_URL=auto
        - VITE_API_PORT=${API_PORT:-3001}  # Explicitly pass Vite env var
    container_name: share-things-frontend  # Explicit container name
    environment:
      - API_PORT=${API_PORT:-3001}
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    volumes:
      - ./client:/app:Z
      - volume-frontend-node-modules:/app/node_modules
    depends_on:
      - backend
    networks:
      app_network:
        aliases:
          - frontend  # Explicit network alias

# Explicit network configuration
networks:
  app_network:
    driver: bridge

# Named volumes for node_modules
volumes:
  volume-backend-node-modules:
  volume-frontend-node-modules: